FROM ubuntu 
RUN apt update 
RUN apt install –y apache2 
RUN apt install –y apache2-utils 
COPY index.html /var/www/html/
RUN apt clean 
EXPOSE 80

# Define the command to run when the container starts
# Apache HTTP server control interface, helps admin to control the frontend http server 
CMD [“apache2ctl”, “-D”, “FOREGROUND”]